FROM node:18-alpine

WORKDIR /app

# Copy your schema.prisma file and any other necessary files
COPY prisma ./prisma/
COPY package.json ./

# Install dependencies including Prisma
RUN npm install
RUN npm install -g prisma

# Expose the port that Prisma Studio runs on
EXPOSE 5555

# Command to run Prisma Studio
CMD ["npx", "prisma", "studio", "--browser", "none", "--hostname", "0.0.0.0"]