services:
  freewise:
    build:
      context: .
    working_dir: /app
    volumes:
      - ./app/:/app/app
      - ./prisma/seed.ts/:/app/prisma/seed.ts
      - /app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      test-db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://test:1234@test-db:5432/freewise?schema=public
      - JWT_SECRET=test
      
  test-db:
    image: postgres:17
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: freewise
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d freewise"]
      interval: 5s
      timeout: 2s
      retries: 20

volumes:
  postgres-data: